### ISSUE TITLE
resize falut

### ISSUE THREAD

**Issue by li-pengcheng** [upura/deep.learning.diabetic.retinopathy#1]
Hi, I‘m missing a problem when I run this main.py code
and the problem as follows:
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
cv2.error: /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

could U please help me to solve it? thanks a lot!

**Comment by upura** [comment]
Hi, @lpengc, 

Thank you for your issue, and I'm so sorry for not recognizing your comment for a long time.  

I think the following link will help you. The problem may occur when you can't read images appropriately.
https://stackoverflow.com/questions/47172770/error-215-ssize-width-0-ssize-height-0-in-function-resize

Sorry for my late reply.
